### ISSUE TITLE
Plugin simply fails to load

### ISSUE THREAD

**Issue by tbhmens** [terminalsin/MemeCheat#3]
Could not load 'plugins\MemeCheat-1.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassFormatError: Arguments can't fit into locals in class file cc/ghast/memecheat/MemeCheat

I think this is a compiler error

**Comment by GhastD** [comment]
Possibly indeed. Will have a look at it.
